### ISSUE TITLE
Error at taas-client l:298 > callback function undefined

### ISSUE THREAD

**Issue by GuySawyer** [TheThingSystem/node-taas-client#7]
Hi

Ran into a weird error while trying to create an event. After looking through the code is when it became weird. The line giving the error seems like it should call a function "callback", but callback is defined as a variable.

Here is my createEvent code:

```
function createLightsensorS1Event(whoami) {
    steward.createEvent('S1lightSensorDark', 'slave1LightDark', whoami, 'light', 'dark', function(message) {        //Observe a dark event from slave1 Light Sensor
    console.log(require('util').inspect(message, { depth: null }));
    });
}
```

the whoami variable contains "device/11". To begin with, let me know if that is not what I should be passing as the "actor" parameter.

This outputs:

```
management
{ path: '/api/v1/event/create/S1lightSensorDark',
  name: 'S1lightSensorDark',
  uuid: 'slave1LightDark',
  actor: 'device/11',
  observe: 'light',
  parameter: '"dark"',
  comments: [Function],
  requestID: 2 }

{ requestID: '2' }

/home/debian/node_modules/taas-client/taas-client.js:298
    callback(message, doneP);
    ^
TypeError: undefined is not a function
    at WebSocket.<anonymous> (/home/debian/node_modules/taas-client/taas-client.js:298:5)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/debian/node_modules/taas-client/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/home/debian/node_modules/taas-client/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/home/debian/node_modules/taas-client/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/home/debian/node_modules/taas-client/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/home/debian/node_modules/taas-client/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
debian@steward:~/node_modules/taas-client$ 
```

The offending code block in taas-client begins at line 261, and the offending function is at 290. Atleast those are the positions in mine. I haven't edited mine.

Help greatly appreciated
Regards
Guy

**Comment by mrose17** [comment]
what is the call you make to create the event, e.g.,

```
    client.createEvent( ... );
```

what does that code look like? thanks!

**Comment by GuySawyer** [comment]
I'm not sure what call you are referring to.
The call I make (to the taas-client) is given above in the first block of code, like this:

```
steward.createEvent('S1lightSensorDark', 'slave1LightDark', whoami, 'light', 'dark', function(message) {        //Observe a dark event from slave1 Light Sensor
    console.log(require('util').inspect(message, { depth: null }));
    });
```

**Comment by mrose17** [comment]
the library should have better bullet-proofing: you're missing the comment parameter, which goes before the callback!

**Comment by GuySawyer** [comment]
Ah, I see. I assumed the library would assign it = "" if no value present. I should have looked closer at the checks.

Thanks

**Comment by mrose17** [comment]
i plan on pushing a fix later this week!
